kotlin.code.style=official
kotlin.dataframe.add.ksp=false
dataframeVersion=1.0.0-dev-10836
dataframeNotebookVersion=1.0.0-dev-10842
dataframeGeoVersion=1.0.0-dev-10836
kandyVersion=0.8.5-dev-102
kandyNotebookVersion=0.8.5-dev-102
kandyGeoVersion=0.8.5-dev-102
#// df should go first!
#%use dataframe(1.0.0-dev-10842)
#%use kandy(0.8.5-dev-102, 0.8.5-dev-102)
#%use kandy-geo(0.8.5-dev-102, 1.0.0-dev-10842)
# Disabling incremental compilation will no longer be necessary
# when https://youtrack.jetbrains.com/issue/KT-66735 is resolved.
kotlin.incremental=true

org.gradle.parallel=false