kotlin.code.style=official
kotlin.dataframe.add.ksp=false
dataframeVersion=1.0.0-Beta5
dataframeNotebookVersion=1.0.0-Beta5n
dataframeGeoVersion=1.0.0-Beta5
kandyVersion=0.8.4
kandyNotebookVersion=0.8.4
kandyGeoVersion=0.8.4
#// df should go first!
#%use dataframe(1.0.0-Beta5n)
#%use kandy(0.8.4, 0.8.4)
#%use kandy-geo(0.8.4, 1.0.0-Beta5n)
# Disabling incremental compilation will no longer be necessary
# when https://youtrack.jetbrains.com/issue/KT-66735 is resolved.
kotlin.incremental=false

org.gradle.parallel=false