kotlin.code.style=official
kotlin.dataframe.add.ksp=false
dataframeVersion=1.0.0-dev-9003
dataframeNotebookVersion=1.0.0-dev-9011
kandyVersion=0.8.3-dev-93
kandyNotebookVersion=0.8.3-dev-93
# %use dataframe(1.0.0-dev-9011), kandy(0.8.3-dev-93, 0.5.1-dev-3)
# Disabling incremental compilation will no longer be necessary
# when https://youtrack.jetbrains.com/issue/KT-66735 is resolved.
kotlin.incremental=false

org.gradle.parallel=false